FROM alpine
RUN apk add unzip
RUN mkdir -p /liferay \
&& cd /liferay \
&& wget http://downloads.sourceforge.net/project/lportal/Liferay%20Portal/6.2.5%20GA6/liferay-portal-tomcat-6.2-ce-ga6-20160112152609836.zip \
&& unzip liferay*.zip
