version: '3.7'
services:
  nginx:
    image: nginx

    container_name: hlxl-nginx

    ports:
      - 9020:80

    volumes:
      - /data/hlxl/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/log:/var/log/nginx

