version: '3.7'
services:
  nginx:
    image: nginx

    container_name: httpserver

    ports:
      - 80:80

    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/dist:/usr/share/nginx/html

